---
name: HTML-Strip-Whitespace
version: 0.1.6
author:
  - 'Shlomi Fish, E<lt>shlomif@iglu.org.ilE<gt>'
abstract: |-
  Perl extension for stripping whitespace out of
  HTML.
license: mit
resources:
  license: http://opensource.org/licenses/mit-license.php
requires:
  Exporter: 0
  HTML::TokeParser::Simple: 0
  strict: 0
  vars: 0
  warnings: 0
build_requires:
  Test::More: 0
provides:
  HTML::Strip::Whitespace:
    file: lib/HTML/Strip/Whitespace.pm
    version: 0.1.6
  HTML::Strip::Whitespace::State:
    file: lib/HTML/Strip/Whitespace.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
